#!/bin/sh

# Assignment2Problem8Script
# Boris Bojanov
# Sep 2026
# Script checks checks if a specified dir exists, creates it if it does not and sends an email. 

username=$(whoami)
echo "$username"
dir_name="$HOME/$1"

# Check if an argument was passed
if [ -z "$1" ]; then 
	echo "Usage: $0 <directory_name>"
	exit 1
fi

# Check if directory exists and is valid
if [ -d "$dir_name" ]; then
	echo "Success: '$dir_name' is a directory."
	echo "Looking for content:"
	ls -l "$dir_name"

else
	echo "Warning: '$dir_name' does not exist or is not a directory. Creating it..."

	if mkdir "$dir_name"; then 
		echo "Made directory '$dir_name' "
		echo "Directory '$dir_name' was created in your home directory. " | mail -s "Directory Modification Notice" "${username}@learn.athabascau.ca"
	else
		echo "Error: Failed to create directory '$dir_name'. Permission denied or invalid path."
		exit 1
		fi

fi
exit 0
