#! /bin/sh

chmod +x ./validate_ip
local ip="$1"
local stat=1

# Check if it matches the general 4-number format separated by dots
if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    # Split the IP into an array using '.' as the separator
    OIFS=$IFS
    IFS='.'
    ip=($ip)
    IFS=$OIFS
    
    # Verify each number is less than or equal to 255
    [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
    stat=$?
fi
return $stat

